### ISSUE TITLE
Cellmap crashes on DEV

### ISSUE THREAD

**Issue by motey** [covidgraph/data_cellmap#1]
```
2020-07-06T11:07:58.501582487Z INFO:__main__:Run parser EnsemblEntityParser
2020-07-06T11:07:58.552061018Z INFO:biodatagraph.parser.ensembl:Start parsing ENSEMBL gtf file, taxid 9606, /download/Ensembl/4fc63d80-a563-433f-a18b-e273a94a0798/gtf/homo_sapiens/Homo_sapiens.GRCh38.release.chr_patch_hapl_scaff.gtf.gz
2020-07-06T11:07:58.553051280Z Traceback (most recent call last):
2020-07-06T11:07:58.553067189Z   File "run.py", line 124, in <module>
2020-07-06T11:07:58.553073409Z     parsers_done.append(run_parser(ensembl_entity_parser))
2020-07-06T11:07:58.553078094Z   File "run.py", line 30, in run_parser
2020-07-06T11:07:58.553082334Z     parser.run_with_mounted_arguments()
2020-07-06T11:07:58.553087096Z   File "/usr/local/lib/python3.8/site-packages/biodatagraph/parser/ensembl.py", line 43, in run_with_mounted_arguments
2020-07-06T11:07:58.553092074Z     self.run(self.taxid)
2020-07-06T11:07:58.553096152Z   File "/usr/local/lib/python3.8/site-packages/biodatagraph/parser/ensembl.py", line 59, in run
2020-07-06T11:07:58.553100603Z     for r in annotation.records:
2020-07-06T11:07:58.553104589Z   File "/usr/local/lib/python3.8/site-packages/biodatagraph/parser/helper/gff.py", line 39, in read_file
2020-07-06T11:07:58.553116372Z     f = gzip.open(self.gff_file_path, 'rt')
2020-07-06T11:07:58.553120585Z   File "/usr/local/lib/python3.8/gzip.py", line 58, in open
2020-07-06T11:07:58.553124771Z     binary_file = GzipFile(filename, gz_mode, compresslevel)
2020-07-06T11:07:58.553128820Z   File "/usr/local/lib/python3.8/gzip.py", line 173, in __init__
2020-07-06T11:07:58.553133165Z     fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
2020-07-06T11:07:58.553137374Z FileNotFoundError: [Errno 2] No such file or directory: '/download/Ensembl/4fc63d80-a563-433f-a18b-e273a94a0798/gtf/homo_sapiens/Homo_sapiens.GRCh38.release.chr_patch_hapl_scaff.gtf.gz'
================================================EXITED with status: 1TIME TOOK: 4.769238343881443 minutes
```

**Comment by mpreusse** [comment]
Wrong dependency for biodatagraph, was 0.0.4 needs to be 0.0.8

**Comment by motey** [comment]
fix confirmed. run successful @ dev
